import { StyleSheet } from 'react-native';
import { FONTS } from '../../constants/FONTS';
import { COLORS } from '../../constants/COLORS';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: COLORS.green950Alpha80,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
  },
  cardWrap: {
    width: '100%',
    maxWidth: 380,
  },
  cardBorder: {
    borderRadius: 28,
    padding: 1,
  },
  card: {
    borderRadius: 27,
    backgroundColor: COLORS.green950Alpha98,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 22,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha05,
  },
  iconBadge: {
    alignSelf: 'center',
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.red300Alpha14,
    borderWidth: 1,
    borderColor: COLORS.red300Alpha28,
    marginBottom: 18,
  },
  title: {
    color: COLORS.white,
    textAlign: 'center',
    fontSize: 24,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    marginBottom: 12,
  },
  warningText: {
    color: COLORS.whiteAlpha72,
    textAlign: 'center',
    fontSize: 15,
    lineHeight: 23,
    fontFamily: FONTS.medium,
    marginBottom: 18,
  },
  tipCard: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: COLORS.whiteAlpha04,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    marginBottom: 14,
  },
  tipLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  tipValue: {
    color: COLORS.primary,
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    letterSpacing: 2,
  },
  inputShell: {
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    backgroundColor: COLORS.whiteAlpha04,
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginBottom: 18,
  },
  input: {
    color: COLORS.white,
    fontSize: 16,
    fontFamily: FONTS.semibold,
    letterSpacing: 1.2,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha12,
    backgroundColor: COLORS.whiteAlpha03,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  primaryButton: {
    flex: 1.2,
    minHeight: 54,
    borderRadius: 18,
    overflow: 'hidden',
  },
  primaryButtonGradient: {
    flex: 1,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  buttonPressed: {
    opacity: 0.92,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
});

export default styles;
