import { Dimensions, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/COLORS';
import { FONTS } from '../../constants/FONTS';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  screenGlowTop: {
    position: 'absolute',
    top: -40,
    alignSelf: 'center',
    width: width * 0.86,
    height: width * 0.86,
    borderRadius: width * 0.43,
    backgroundColor: COLORS.yellow300Alpha18,
    opacity: 0.75,
  },
  screenGlowBottom: {
    position: 'absolute',
    bottom: 120,
    alignSelf: 'center',
    width: width * 0.95,
    height: width * 0.95,
    borderRadius: width * 0.475,
    backgroundColor: COLORS.lime400Alpha06,
    opacity: 0.42,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  profileChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.whiteAlpha10,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileText: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.bold,
    fontSize: 14,
    letterSpacing: FONTS.letterSpacing.wide,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.whiteAlpha08,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
  },
  coinCluster: {
    width: 250,
    height: 166,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  coinAura: {
    position: 'absolute',
    top: 10,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: COLORS.yellow300Alpha16,
    opacity: 0.8,
  },
  coinBaseGlow: {
    position: 'absolute',
    bottom: 18,
    width: 130,
    height: 24,
    borderRadius: 999,
    backgroundColor: COLORS.lime400Alpha40,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.4,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  orbitLayer: {
    position: 'absolute',
    width: 240,
    height: 170,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orbitSvg: {
    position: 'absolute',
  },
  coinBadge: {
    width: 108,
    height: 108,
    borderRadius: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha22,
  },
  coinBadgeInner: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha24,
    backgroundColor: COLORS.yellow700Alpha22,
  },
  rateText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.medium,
    fontSize: 12,
    letterSpacing: FONTS.letterSpacing.normal,
    marginBottom: 6,
  },
  amountText: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.black,
    fontSize: 42,
    lineHeight: 46,
    letterSpacing: FONTS.letterSpacing.tight,
    marginBottom: 0,
  },
  ringSection: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  actionSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginVertical: 15,
  },
  actionFooter: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  actionButtonsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  timerCore: {
    width: 190,
    height: 190,
    borderRadius: 95,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    overflow: 'hidden',
  },
  timerCoreGlow: {
    position: 'absolute',
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: COLORS.lime300Alpha12,
  },
  playButton: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.whiteAlpha12,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha12,
    marginBottom: 18,
  },
  playIcon: {
    marginLeft: 4,
  },
  storageLabel: {
    color: COLORS.textMuted,
    fontFamily: FONTS.medium,
    fontSize: 12,
    letterSpacing: FONTS.letterSpacing.wide,
    marginBottom: 6,
  },
  timerText: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.black,
    fontSize: 34,
    lineHeight: 38,
    letterSpacing: FONTS.letterSpacing.tight,
  },
  statsCard: {
    marginHorizontal: 20,
    marginBottom: 18,
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: COLORS.glassBorder,
    backgroundColor: COLORS.cardMuted,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statsLabel: {
    color: COLORS.textMuted,
    fontFamily: FONTS.medium,
    fontSize: 16,
    letterSpacing: FONTS.letterSpacing.ultraWide,
    marginBottom: -10,
    marginTop: 8,
  },
  statsTitle: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.bold,
    fontSize: 18,
    lineHeight: 22,
  },
  statusBadge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: COLORS.lime300Alpha16,
    borderWidth: 1,
    borderColor: COLORS.lime300Alpha26,
  },
  statusBadgeText: {
    color: COLORS.success,
    fontFamily: FONTS.bold,
    fontSize: 11,
    letterSpacing: FONTS.letterSpacing.ultraWide,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.whiteAlpha08,
    marginBottom: 16,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metricBlock: {
    flex: 1,
    alignItems: 'center',
  },
  metricValue: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.bold,
    fontSize: 22,
    lineHeight: 26,
    marginBottom: 4,
    textAlign: 'center',
  },
  metricCaption: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
});

export default styles;
