export const FLOATING_TAB_BAR_BASE_HEIGHT = 74;
export const FLOATING_TAB_BAR_BOTTOM_OFFSET = 12;

export const MINING_LIVE_BAR_HEIGHT = 72;
export const MINING_LIVE_BAR_GAP = 12;
export const MINING_LIVE_BAR_HORIZONTAL_MARGIN = 16;
