import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/COLORS';
import { FONTS } from '../../constants/FONTS';
import { THEME } from './theme';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    backgroundColor: COLORS.green950Alpha72,
  },
  keyboardWrap: {
    width: '100%',
  },
  card: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 24,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 24,
    backgroundColor: COLORS.green900Alpha98,
    borderWidth: 1,
    borderColor: COLORS.lime500Alpha16,
    shadowColor: COLORS.black,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 18,
  },
  closeButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.whiteAlpha05,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrap: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.lime500Alpha12,
    borderWidth: 1,
    borderColor: COLORS.lime500Alpha16,
    marginBottom: 16,
  },
  title: {
    color: THEME.white,
    fontSize: 22,
    lineHeight: 28,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 8,
    color: THEME.textMuted,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONTS.medium,
  },
  amountCard: {
    marginTop: 18,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: COLORS.whiteAlpha04,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  amountLabel: {
    color: COLORS.whiteAlpha54,
    fontSize: 12,
    fontFamily: FONTS.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  amountValue: {
    marginTop: 6,
    color: THEME.neonGreen,
    fontSize: 24,
    fontFamily: FONTS.black,
    fontWeight: '800',
  },
  fieldGroup: {
    marginTop: 18,
  },
  fieldLabel: {
    color: THEME.white,
    fontSize: 13,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    minHeight: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    backgroundColor: COLORS.whiteAlpha04,
    paddingHorizontal: 16,
    color: THEME.white,
    fontSize: 15,
    fontFamily: FONTS.medium,
  },
  inputError: {
    borderColor: COLORS.danger,
  },
  helperText: {
    marginTop: 8,
    color: COLORS.whiteAlpha54,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: FONTS.medium,
  },
  errorText: {
    marginTop: 8,
    color: COLORS.danger,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: FONTS.medium,
  },
  buttonRow: {
    flexDirection: 'row',
    marginTop: 22,
  },
  buttonSpacer: {
    width: 12,
  },
  button: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  cancelButton: {
    backgroundColor: COLORS.whiteAlpha04,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  cancelButtonText: {
    color: THEME.white,
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  submitButtonWrap: {
    flex: 1,
    borderRadius: 18,
    overflow: 'hidden',
  },
  submitPressable: {
    flex: 1,
    borderRadius: 18,
  },
  submitButton: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: THEME.neonGreen,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: COLORS.neutral950,
    fontSize: 15,
    fontFamily: FONTS.black,
    fontWeight: '800',
  },
});

export default styles;
