import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../constants/COLORS'
import { THEME, formatAmount } from '../../components/wallet/theme';
import { FONTS } from '../../constants/FONTS';


const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: THEME.bg,
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: COLORS.green950Alpha58,
  },
  topGlow: {
    position: 'absolute',
    top: 90,
    right: -32,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.green300Alpha08Tone2,
  },
  bottomGlow: {
    position: 'absolute',
    bottom: 160,
    left: -24,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: COLORS.lime500Alpha08Tone2,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 4,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  headerRowSafe: {
    paddingTop: 12,
  },
  walletTitle: {
    color: THEME.white,
    fontSize: 30,
    fontFamily: FONTS.black,
    fontWeight: '800',
  },
  receiptButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: COLORS.whiteAlpha06,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adContainer: {
    alignItems: 'center',
    marginVertical: 16,
    width: '100%',
  },
  liquidWalletCard: {
    marginHorizontal: 18,
    borderRadius: 32,
    borderWidth: 1.5,
    borderColor: COLORS.lime400Alpha64,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 18,
    shadowColor: COLORS.lime500Alpha55,
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 18,
  },
  heroGlowPrimary: {
    position: 'absolute',
    top: -36,
    right: -24,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: COLORS.green200Alpha12,
  },
  heroGlowSecondary: {
    position: 'absolute',
    bottom: -36,
    left: -28,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: COLORS.teal300Alpha07,
  },
  heroBorderOverlay: {
    ...StyleSheet.absoluteFill,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: COLORS.lime200Alpha12,
  },
  liquidWalletBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: COLORS.green900Alpha62,
    borderWidth: 1,
    borderColor: COLORS.lime300Alpha18,
  },
  badgeIcon: {
    marginRight: 6,
  },
  liquidWalletBadgeText: {
    color: COLORS.lime300Tone2,
    fontSize: 14,
    fontFamily: FONTS.medium,
    fontWeight: '600',
  },
  balanceBlock: {
    minHeight: 164,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
  },
  balanceAmount: {
    color: THEME.white,
    fontSize: 52,
    lineHeight: 74,
    fontFamily: FONTS.black,
    fontWeight: '900',
    textAlign: 'center',
  },
  balanceUnit: {
    color: THEME.neonGreen,
    fontSize: 30,
    fontFamily: FONTS.regular,
  },
  balanceCaption: {
    marginTop: 8,
    color: COLORS.whiteSoft,
    fontSize: 15,
    fontFamily: FONTS.medium,
    textAlign: 'center',
  },
  pendingPill: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: COLORS.green800Alpha78,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  pendingPillText: {
    color: COLORS.whiteAlpha84,
    fontSize: 13,
    fontFamily: FONTS.medium,
  },
  balanceSkeletonWrap: {
    alignItems: 'center',
    gap: 12,
  },
  balanceSkeletonAmount: {
    width: 220,
    height: 52,
    borderRadius: 18,
    backgroundColor: COLORS.whiteAlpha10,
  },
  balanceSkeletonCaption: {
    width: 190,
    height: 14,
    borderRadius: 999,
    backgroundColor: COLORS.whiteAlpha08,
  },
  balanceSkeletonPill: {
    width: 126,
    height: 34,
    borderRadius: 999,
    backgroundColor: COLORS.whiteAlpha08,
  },
  withdrawActionWrap: {
    marginTop: 8,
  },
  withdrawAction: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  withdrawActionPressed: {
    opacity: 0.94,
  },
  withdrawActionDisabled: {
    opacity: 0.6,
  },
  withdrawActionGradient: {
    minHeight: 96,
    paddingHorizontal: 16,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.lime300Alpha20,
  },
  withdrawActionIconBox: {
    width: 62,
    height: 62,
    borderRadius: 18,
    backgroundColor: COLORS.green900Alpha64,
    borderWidth: 1,
    borderColor: COLORS.lime500Alpha18Tone2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  withdrawActionCopy: {
    flex: 1,
    paddingHorizontal: 14,
  },
  withdrawActionTitle: {
    color: THEME.white,
    fontSize: 20,
    fontFamily: FONTS.black,
    fontWeight: '900',
    letterSpacing: 1,
  },
  withdrawActionSubtitle: {
    marginTop: 4,
    color: COLORS.whiteAlpha72,
    fontSize: 13,
    fontFamily: FONTS.medium,
  },
  withdrawActionArt: {
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overviewSection: {
    marginTop: 18,
    paddingHorizontal: 18,
  },
  overviewTitle: {
    color: THEME.white,
    fontSize: 22,
    fontFamily: FONTS.black,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.8,
  },
  overviewGrid: {
    flexDirection: 'row',
    marginTop: 14,
  },
  overviewCard: {
    flex: 1,
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 18,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: COLORS.lime300Alpha38Tone2,
    shadowColor: COLORS.lime500Alpha24,
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  overviewCardSpacing: {
    marginRight: 10,
  },
  overviewIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  overviewLabel: {
    color: COLORS.whiteAlpha82,
    fontSize: 13,
    fontFamily: FONTS.medium,
  },
  overviewValue: {
    marginTop: 8,
    color: THEME.white,
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    textAlign: 'center',
  },
  overviewUnit: {
    color: THEME.neonGreen,
    fontSize: 12,
    fontFamily: FONTS.bold,
  },
  overviewSkeletonLine: {
    width: '82%',
    height: 16,
    borderRadius: 999,
    backgroundColor: COLORS.whiteAlpha10,
    marginTop: 8,
  },
  withdrawalsSection: {
    marginTop: 20,
    marginBottom: 4,
  },
});

export default styles;
