import {
  ActivityIndicator,
  Dimensions,
  Image,
  Pressable,
  RefreshControl,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { COLORS } from '../../constants/COLORS';
import { FONTS } from '../../constants/FONTS';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#020705',
  },
  absoluteFill: {
    ...StyleSheet.absoluteFill,
  },
  safeArea: {
    flex: 1,
  },
  avatarImageFill: {
    ...StyleSheet.absoluteFill,
  },
  radialGlow: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    opacity: 0.55,
  },
  radialGlowTop: {
    top: -80,
    left: -70,
    backgroundColor: 'rgba(136, 255, 84, 0.09)',
  },
  radialGlowBottom: {
    right: -90,
    bottom: 110,
    backgroundColor: 'rgba(91, 255, 168, 0.06)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 12,
  },
  headerAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  headerActionPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.96 }],
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  headerSubtitle: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.54)',
    fontSize: 12,
    fontFamily: FONTS.medium,
    letterSpacing: 0.3,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 6,
  },
  heroCard: {
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: 'rgba(9, 17, 12, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(185,255,102,0.16)',
    marginBottom: 0,
  },
  heroEyebrow: {
    color: '#B9FF66',
    fontSize: 11,
    fontFamily: FONTS.medium,
    letterSpacing: 1.3,
  },
  heroTitle: {
    marginTop: 8,
    color: '#FFFFFF',
    fontSize: 24,
    lineHeight: 31,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  heroBody: {
    marginTop: 10,
    color: 'rgba(255,255,255,0.66)',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONTS.regular,
  },
  podiumSection: {
    minHeight: 330,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: -80,
  },
  podiumItem: {
    alignItems: 'center',
  },
  podiumItemFirst: {
    width: width * 0.33,
    marginBottom: 15,
  },
  podiumItemSide: {
    width: width * 0.275,
  },
  avatarBlock: {
    marginBottom: -18,
    zIndex: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  podiumIconBadge: {
    position: 'absolute',
    top: -8,
    zIndex: 5,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  avatarGradient: {
    padding: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInnerCircle: {
    flex: 1,
    width: '100%',
    overflow: 'hidden',
    backgroundColor: '#111A14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    color: '#FFFFFF',
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  rankOneGlow: {
    position: 'absolute',
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 2,
    borderColor: 'rgba(176, 255, 87, 0.95)',
    backgroundColor: 'rgba(176,255,87,0.06)',
  },
  podiumCard: {
    width: '100%',
    borderRadius: 26,
    paddingTop: 28,
    paddingHorizontal: 12,
    paddingBottom: 16,
    alignItems: 'center',
    justifyContent: 'flex-end',
    borderWidth: 1,
  },
  podiumCardFirst: {
    shadowColor: '#AEFF57',
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  rankChip: {
    minWidth: 40,
    height: 24,
    borderRadius: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    marginBottom: 10,
  },
  rankChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  podiumName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    maxWidth: '100%',
  },
  podiumEmail: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.42)',
    fontSize: 10,
    fontFamily: FONTS.regular,
    maxWidth: '100%',
  },
  podiumAmount: {
    marginTop: 10,
    color: '#B9FF66',
    fontSize: 14,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  podiumMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  podiumMetaText: {
    marginLeft: 5,
    color: 'rgba(255,255,255,0.56)',
    fontSize: 11,
    fontFamily: FONTS.medium,
  },
  youCard: {
    marginBottom: 22,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(185,255,102,0.16)',
  },
  youCardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  youRankPill: {
    minWidth: 44,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(185,255,102,0.14)',
    marginRight: 10,
  },
  youRankPillText: {
    color: '#D4FF9A',
    fontSize: 13,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  youInfo: {
    flex: 1,
    marginLeft: 12,
    marginRight: 12,
  },
  youName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  youSubtitle: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.56)',
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  youAmountWrap: {
    alignItems: 'flex-end',
  },
  youAmount: {
    color: '#B9FF66',
    fontSize: 17,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  youAmountUnit: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.48)',
    fontSize: 11,
    fontFamily: FONTS.medium,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  listHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  listHeaderSubtitle: {
    color: 'rgba(255,255,255,0.46)',
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  listContainer: {
    gap: 12,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: 'rgba(10, 18, 12, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  listItemHighlight: {
    borderColor: 'rgba(185,255,102,0.18)',
    backgroundColor: 'rgba(185,255,102,0.05)',
  },
  listRankWrap: {
    width: 42,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  listRank: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 14,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  listRankHighlight: {
    color: '#B9FF66',
  },
  listInfo: {
    flex: 1,
    marginLeft: 12,
    marginRight: 10,
  },
  listName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  listNameHighlight: {
    color: '#D7FF9C',
  },
  listMeta: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.40)',
    fontSize: 11,
    fontFamily: FONTS.regular,
  },
  listSubMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  listSubMetaText: {
    marginLeft: 5,
    color: 'rgba(255,255,255,0.56)',
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  listAmountWrap: {
    alignItems: 'flex-end',
  },
  listAmount: {
    color: '#AFFF57',
    fontSize: 17,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  listAmountHighlight: {
    color: '#D4FF96',
  },
  listAmountUnit: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.44)',
    fontSize: 11,
    fontFamily: FONTS.medium,
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    marginTop: 40,
  },
  stateIconWrap: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  stateTitle: {
    marginTop: 18,
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    textAlign: 'center',
  },
  stateMessage: {
    marginTop: 8,
    color: 'rgba(255,255,255,0.58)',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONTS.regular,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 18,
    height: 44,
    borderRadius: 22,
    paddingHorizontal: 18,
    backgroundColor: '#B9FF66',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  retryButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  retryButtonText: {
    marginLeft: 8,
    color: '#08110C',
    fontSize: 14,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  emptyState: {
    borderRadius: 24,
    paddingVertical: 36,
    paddingHorizontal: 24,
    alignItems: 'center',
    backgroundColor: 'rgba(9, 15, 11, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  emptyTitle: {
    marginTop: 16,
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    color: 'rgba(255,255,255,0.54)',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONTS.regular,
    textAlign: 'center',
  },
});

export default styles;
