import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/COLORS';
import { FONTS } from '../../constants/FONTS';

const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  primaryGlow: {
    position: 'absolute',
    top: -80,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: COLORS.lime500Alpha12,
    opacity: 0.9,
  },
  secondaryGlow: {
    position: 'absolute',
    right: -40,
    bottom: 70,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: COLORS.green500Alpha15,
    opacity: 0.85,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: {
    color: COLORS.textPrimary,
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  settingsButton: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  scrollContent: {
    paddingTop: 16,
    paddingHorizontal: 18,
  },
  profileCard: {
    backgroundColor: COLORS.green950Alpha98Tone2,
    borderRadius: 28,
    overflow: 'hidden',
    marginBottom: 26,
    borderWidth: 1,
    borderColor: COLORS.lime500Alpha16,
    shadowColor: COLORS.lime500,
    shadowOpacity: 0.16,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  profileCover: {
    position: 'relative',
    height: 118,
    overflow: 'hidden',
  },
  cloudOne: {
    position: 'absolute',
    top: 20,
    left: 34,
    width: 82,
    height: 38,
    borderRadius: 24,
    backgroundColor: COLORS.lime500Alpha12,
  },
  cloudTwo: {
    position: 'absolute',
    top: 30,
    left: 82,
    width: 118,
    height: 48,
    borderRadius: 26,
    backgroundColor: COLORS.green300Alpha28,
  },
  cloudThree: {
    position: 'absolute',
    top: 18,
    left: 152,
    width: 92,
    height: 40,
    borderRadius: 24,
    backgroundColor: COLORS.lime500Alpha08Tone2,
  },
  profileTopAction: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: COLORS.green950Alpha80,
    borderWidth: 1,
    borderColor: COLORS.lime500Alpha18,
    shadowColor: COLORS.lime500,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  profileTopActionPressed: {
    opacity: 0.86,
  },
  profileTopActionText: {
    color: COLORS.textPrimary,
    fontSize: 13,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    marginRight: 4,
  },
  profileSection: {
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  profileIdentityRow: {
    marginTop: -34,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  avatarShell: {
    marginRight: 14,
  },
  avatarPulseRing: {
    position: 'absolute',
    top: -3,
    left: -3,
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: COLORS.lime500Alpha18,
  },
  avatarGlow: {
    padding: 4,
    borderRadius: 44,
    backgroundColor: COLORS.green500Alpha15,
  },
  avatarBorder: {
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 4,
    borderColor: COLORS.lime400,
    overflow: 'hidden',
    backgroundColor: COLORS.green900Tone2,
  },
  avatar: {
    width: '100%',
    height: '100%',
    borderRadius: 37,
  },
  avatarFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    color: COLORS.textPrimary,
    fontSize: 30,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  identityContent: {
    flex: 1,
    minWidth: 0,
    paddingTop: 38,
  },
  profileMiniMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  profileMiniMetaLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontFamily: FONTS.medium,
    marginRight: 8,
  },
  profileMiniBarTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 92,
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: COLORS.whiteAlpha08,
  },
  profileMiniBarSegment: {
    height: '100%',
  },
  profileMiniBarSegmentMining: {
    backgroundColor: COLORS.primary,
  },
  profileMiniBarSegmentReward: {
    backgroundColor: COLORS.teal300,
  },
  profileMiniBarSegmentReferral: {
    backgroundColor: COLORS.green300Tone2,
  },
  userName: {
    color: COLORS.textPrimary,
    fontSize: 29,
    lineHeight: 34,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  profileSubtitle: {
    color: COLORS.whiteAlpha72,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: FONTS.regular,
    marginTop: 8,
  },
  userHandle: {
    color: COLORS.primary,
    fontSize: 13,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    marginTop: 10,
  },
  emailPlain: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
    marginTop: 4,
  },
  profileStatsRow: {
    flexDirection: 'row',
    marginTop: 22,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  profileStatCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  profileStatCardSpacing: {
    borderRightWidth: 1,
    borderRightColor: COLORS.whiteAlpha08,
  },
  profileStatValue: {
    color: COLORS.textPrimary,
    fontSize: 24,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  profileStatLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
    marginTop: 5,
  },
  profileQuickRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 14,
  },
  profileQuickIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.whiteAlpha06,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha08,
  },
  adContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 26,
    marginTop: -10,
  },
  section: {
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  sectionLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    marginTop: 4,
    color: COLORS.textPrimary,
    fontSize: 22,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  sectionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  sectionBadgeText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
});

export default styles;
