import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
  TouchableOpacity,
  Image,
  StatusBar,
  Animated,
  Alert,
} from 'react-native';
import { COLORS } from '../../constants/COLORS';
import { FONTS } from '../../constants/FONTS';

const styles = StyleSheet.create({
  background: { flex: 1 },
  adContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 26,
    marginTop: -10,
  },
  container: { flex: 1 },
  primaryGlow: {
    position: 'absolute',
    top: -60,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: COLORS.surfaceGlow,
    opacity: 0.34,
  },
  secondaryGlow: {
    position: 'absolute',
    right: -50,
    bottom: 80,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.ringGlowSoft,
    opacity: 0.3,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: { color: COLORS.textPrimary, fontSize: 18, fontWeight: 'bold' },
  settingsButton: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  scrollContent: {
    paddingTop: 16,
    paddingHorizontal: 18,
  },
  profileCard: {
    borderRadius: 30,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(198,255,112,0.14)',
    marginBottom: 26,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  profileCardGlow: {
    position: 'absolute',
    top: -30,
    right: -10,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(170,255,0,0.08)',
  },
  profileSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 22,
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarShell: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  avatarPulseRing: {
    position: 'absolute',
    width: 136,
    height: 136,
    borderRadius: 68,
    backgroundColor: 'rgba(170,255,0,0.08)',
  },
  avatarGlow: {
    padding: 10,
    borderRadius: 72,
    backgroundColor: 'rgba(57, 255, 20, 0.12)',
    shadowColor: '#20321dff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 18,
    elevation: 12,
  },
  avatarBorder: {
    width: 112,
    height: 112,
    borderRadius: 56,
    borderWidth: 2,
    borderColor: '#39FF14',
    padding: 4,
    backgroundColor: 'rgba(10,15,10,0.72)',
  },
  avatar: { width: '100%', height: '100%', borderRadius: 52 },
  avatarFallback: {
    width: '100%',
    height: '100%',
    borderRadius: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    color: COLORS.textPrimary,
    fontSize: 36,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  identityPill: {
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  identityPillText: {
    color: COLORS.primary,
    fontSize: 12,
    fontFamily: FONTS.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  identityContent: {
    flex: 1,
    alignItems: 'flex-start',
  },
  userName: {
    color: COLORS.textPrimary,
    fontSize: 27,
    fontWeight: '800',
    marginTop: 12,
  },
  userHandle: {
    color: COLORS.primary,
    fontSize: 14,
    fontFamily: FONTS.medium,
    marginTop: 4,
  },
  userMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  userMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: '100%',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginRight: 8,
    marginBottom: 8,
  },
  userMetaText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
    marginLeft: 6,
  },
  profileStatsRow: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 18,
  },
  profileStatCard: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  profileStatCardSpacing: {
    marginRight: 12,
  },
  profileStatLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  profileStatValue: {
    marginTop: 6,
    color: COLORS.textPrimary,
    fontSize: 17,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  profilePrimaryAction: {
    width: '100%',
    marginTop: 14,
    borderRadius: 18,
    overflow: 'hidden',
  },
  profilePrimaryActionPressed: {
    opacity: 0.92,
  },
  profilePrimaryActionInner: {
    minHeight: 52,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(170,255,0,0.14)',
  },
  profilePrimaryActionText: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
  },
  section: {
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  sectionLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    marginTop: 4,
    color: COLORS.textPrimary,
    fontSize: 22,
    fontFamily: FONTS.bold,
    fontWeight: '800',
  },
  sectionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  sectionBadgeText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
});

export default styles;
