import {
  Clipboard,
  Pressable,
  ScrollView,
  Share,
  StatusBar,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { FONTS } from '../../constants/FONTS';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#090d08',
  },
  safeArea: {
    flex: 1,
  },
  primaryGlow: {
    position: 'absolute',
    top: 90,
    alignSelf: 'center',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(170, 255, 0, 0.09)',
    transform: [{ scaleX: 1.08 }],
  },
  secondaryGlow: {
    position: 'absolute',
    top: 360,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(170, 255, 0, 0.05)',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
    elevation: 10,
  },
  backButtonWrap: {
    width: 54,
    alignItems: 'flex-start',
  },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
  },
  headerSpacer: {
    width: 54,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  heroSection: {
    alignItems: 'center',
    marginTop: 28,
    marginBottom: 26,
  },
  giftHalo: {
    width: 260,
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lottieIcon: {
    width: 320,
    height: 320,
    marginTop: -240,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 34,
    textAlign: 'center',
    fontFamily: FONTS.black,
    fontWeight: '800',
    marginTop: -130,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 16,
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: FONTS.medium,
    fontWeight: '500',
    marginTop: 14,
  },
  highlightText: {
    color: '#B7FF31',
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    marginBottom: 22,
  },
  statCard: {
    flex: 1,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(16, 22, 14, 0.78)',
  },
  statCardSpacing: {
    marginRight: 12,
  },
  statCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  statLabel: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  statValue: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: FONTS.black,
    fontWeight: '800',
  },
  statHint: {
    marginTop: 8,
    color: '#B7FF31',
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
    marginHorizontal: 10,
    marginBottom: 24,
  },
  card: {
    marginBottom: 16,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(16, 22, 14, 0.78)',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  cardLabel: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 14,
  },
  referralCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingLeft: 16,
    paddingRight: 8,
    paddingVertical: 10,
  },
  referralCodeText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    marginRight: 10,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    width: 44,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    marginLeft: 6,
  },
  actionButtonPressed: {
    opacity: 0.88,
  },
  redeemRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    color: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 14,
    fontFamily: FONTS.medium,
    marginRight: 10,
  },
  inputDisabled: {
    opacity: 0.7,
  },
  claimButton: {
    height: 52,
    minWidth: 90,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#B7FF31',
    shadowColor: '#B7FF31',
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  claimButtonPressed: {
    opacity: 0.92,
  },
  claimButtonDisabled: {
    shadowOpacity: 0,
  },
  claimButtonText: {
    color: '#10140b',
    fontSize: 15,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  helperText: {
    marginTop: 14,
    color: 'rgba(255,255,255,0.48)',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: FONTS.medium,
  },
});

export default styles;
