import {
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';
import { FONTS } from '../../constants/FONTS';
import { TICKET_THEME } from '../../components/tickets/ticketTheme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: TICKET_THEME.background,
  },
  content: {
    paddingHorizontal: 18,
  },
  helpCard: {
    backgroundColor: '#14210F',
    borderColor: TICKET_THEME.cardBorder,
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    marginBottom: 20,
  },
  helpIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: TICKET_THEME.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  helpTextWrap: {
    flex: 1,
  },
  helpTitle: {
    color: TICKET_THEME.accent,
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  helpDescription: {
    color: TICKET_THEME.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  previousReportsCard: {
    marginBottom: 6,
    backgroundColor: TICKET_THEME.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: TICKET_THEME.cardBorder,
    overflow: 'hidden',
  },
  previousReportsHeader: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  previousReportsTitle: {
    color: TICKET_THEME.textPrimary,
    fontSize: 17,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    flex: 1,
    paddingTop: 6,
    paddingRight: 16,
  },
  previousReportsActions: {
    alignItems: 'center',
    gap: 8,
  },
  expandIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: TICKET_THEME.input,
  },
  viewAllButton: {
    minHeight: 24,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAllButtonText: {
    color: TICKET_THEME.accent,
    fontSize: 12,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
  },
  previousReportsContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  compactState: {
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: TICKET_THEME.input,
    borderWidth: 1,
    borderColor: TICKET_THEME.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportPreviewList: {
    gap: 10,
  },
  reportPreviewItem: {
    borderRadius: 16,
    padding: 14,
    backgroundColor: TICKET_THEME.input,
    borderWidth: 1,
    borderColor: TICKET_THEME.inputBorder,
  },
  reportPreviewTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  reportPreviewCategory: {
    flex: 1,
    color: TICKET_THEME.textPrimary,
    fontSize: 15,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
  },
  reportPreviewStatus: {
    color: TICKET_THEME.pending,
    fontSize: 11,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  reportPreviewDescription: {
    marginTop: 8,
    color: TICKET_THEME.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  reportPreviewFooter: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reportPreviewMeta: {
    flex: 1,
    color: TICKET_THEME.textMuted,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  label: {
    color: TICKET_THEME.textPrimary,
    fontSize: 17,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 14,
  },
  selector: {
    backgroundColor: TICKET_THEME.input,
    borderWidth: 1,
    borderColor: TICKET_THEME.inputBorder,
    borderRadius: 16,
    minHeight: 56,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorText: {
    color: TICKET_THEME.textPrimary,
    fontSize: 16,
  },
  placeholderText: {
    color: TICKET_THEME.textMuted,
  },
  descriptionInput: {
    minHeight: 150,
    borderRadius: 18,
    backgroundColor: TICKET_THEME.input,
    borderColor: TICKET_THEME.inputBorder,
    borderWidth: 1,
    color: TICKET_THEME.textPrimary,
    padding: 16,
    fontSize: 15,
    lineHeight: 22,
  },
  contactCard: {
    backgroundColor: TICKET_THEME.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: TICKET_THEME.cardBorder,
    padding: 16,
    marginTop: 18,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contactCopy: {
    flex: 1,
    paddingRight: 16,
  },
  contactTitle: {
    color: TICKET_THEME.textPrimary,
    fontSize: 17,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
  },
  contactDescription: {
    color: TICKET_THEME.textSecondary,
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
  },
  contactFields: {
    marginTop: 14,
    gap: 12,
  },
  singleLineInput: {
    height: 52,
    borderRadius: 14,
    backgroundColor: TICKET_THEME.input,
    borderWidth: 1,
    borderColor: TICKET_THEME.inputBorder,
    color: TICKET_THEME.textPrimary,
    paddingHorizontal: 14,
    fontSize: 15,
  },
  submitButton: {
    marginTop: 22,
    backgroundColor: TICKET_THEME.accent,
    minHeight: 58,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: TICKET_THEME.background,
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '700',
  },
  emptyTitle: {
    color: TICKET_THEME.textPrimary,
    fontSize: 17,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
  },
  emptyDescription: {
    color: TICKET_THEME.textSecondary,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: TICKET_THEME.cardStrong,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: TICKET_THEME.cardBorder,
  },
  modalTitle: {
    color: TICKET_THEME.textPrimary,
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    marginBottom: 12,
  },
  modalOption: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: TICKET_THEME.input,
    paddingHorizontal: 14,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalOptionText: {
    color: TICKET_THEME.textPrimary,
    fontSize: 15,
  },
});

export default styles;
